export const itensSelecionaveis =  {
  ufs: [
    {text: 'AC - Acre', value: 'AC'},
    {text: 'AL - Alagoas', value: 'AL'},
    {text: 'AP - Amapá', value: 'AP'},
    {text: 'AM - Amazonas', value: 'AM'},
    {text: 'BA - Bahia', value: 'BA'},
    {text: 'CE - Ceará', value: 'CE'},
    {text: 'DF - Distrito Federal', value: 'DF'},
    {text: 'ES - Espírito Santo', value: 'ES'},
    {text: 'GO - Goiás', value: 'GO'},
    {text: 'MA - Maranhão', value: 'MA'},
    {text: 'MT - Mato Grosso', value: 'MT'},
    {text: 'MS - Mato Grosso do Sul', value: 'MS'},
    {text: 'MG - Minas Gerais', value: 'MG'},
    {text: 'PA - Pará', value: 'PA'},
    {text: 'PB - Paraíba', value: 'PB'},
    {text: 'PR - Paraná', value: 'PR'},
    {text: 'PE - Pernambuco', value: 'PE'},
    {text: 'PI - Piauí', value: 'PI'},
    {text: 'RJ - Rio de Janeiro', value: 'RJ'},
    {text: 'RN - Rio Grande do Norte', value: 'RN'},
    {text: 'RS - Rio Grande do Sul', value: 'RS'},
    {text: 'RO - Rondônia', value: 'RO'},
    {text: 'RR - Roraima', value: 'RR'},
    {text: 'SC - Santa Catarina', value: 'SC'},
    {text: 'SP - São Paulo', value: 'SP'},
    {text: 'SE - Sergipe', value: 'SE'},
    {text: 'TO - Tocantins', value: 'TO'},
  ],
  produtos: [
    { value: 3603, text: 'SaaSPDV' },
    { value: 3604, text: 'SaaSERP' },
    { value: 3605, text: 'SaaSReports' },
    { value: 3607, text: 'SaaSTEC' },
    { value: 6001, text: 'SaaSFin' },
    { value: 8101, text: 'SaaSEcomm' },
  ],
  os: [
    {value: 1, text: 'Windows'},
    {value: 2, text: 'MacOS'},
    {value: 3, text: 'Linux'},
  ],
  segmentos: [
    { value: 1 , text: "Aviário" },
    { value: 2 , text: "Comércio de acessórios automotivos" },
    { value: 3 , text: "Comércio de artigos usados" },
    { value: 4 , text: "Comércio de brindes" },
    { value: 5 , text: "Comércio de calçados" },
    { value: 6 , text: "Comércio de carnes" },
    { value: 7 , text: "Comércio de colchões" },
    { value: 8 , text: "Comércio de cosméticos" },
    { value: 9 , text: "Comércio de eletrodomésticos" },
    { value: 10, text: "Comercio de embalagens" },
    { value: 11, text: "Comércio de EPI" },
    { value: 12, text: "Comércio de informática/eletrônicos" },
    { value: 13, text: "Comércio de instrumentos musicais" },
    { value: 14, text: "Comércio de máquinas" },
    { value: 15, text: "Comércio de móveis" },
    { value: 16, text: "Comercio de peixes e frutos do mar" },
    { value: 17, text: "Comércio de presentes" },
    { value: 18, text: "Comércio de produtos hospitalares" },
    { value: 19, text: "Comércio de produtos naturais" },
    { value: 20, text: "Comércio de roupas" },
    { value: 21, text: "Comércio de sistemas de segurança" },
    { value: 22, text: "Comércio de utensílios domésticos" },
    { value: 23, text: "Distribuidora de bebidas" },
    { value: 24, text: "Distribuidora de gás" },
    { value: 25, text: "Distribuidora de produtos alimentícios" },
    { value: 26, text: "Indústria de bebidas" },
    { value: 27, text: "Indústria de confecções" },
    { value: 28, text: "Indústria de reciclagem" },
    { value: 29, text: "Joalheria" },
    { value: 30, text: "Livraria ou sebo" },
    { value: 31, text: "Material de construção" },
    { value: 32, text: "Minimercado" },
    { value: 33, text: "Ótica" },
    { value: 34, text: "Panificadora" },
    { value: 35, text: "Papelaria" },
    { value: 36, text: "Petshop" },
    { value: 37, text: "Pizzaria" },
    { value: 38, text: "Restaurante" },
    { value: 39, text: "Salões de beleza" },
    { value: 40, text: "Serviços residenciais" },
    { value: 99, text: "Outros" },

  ],
  planos: [
    {text: 'Premium', value: 1},
    {text: 'Essencial', value: 2},
    {text: 'Básico', value: 3},
  ],
  migracao: [
    { text: 'Produtos'        , value: 1 },
    { text: 'Clientes'        , value: 2 },
    { text: 'Fornecedores'    , value: 3 },
    { text: 'Contas a pagar'  , value: 4 },
    { text: 'Contas a receber', value: 5 },
    { text: 'Crediário'       , value: 6 },
  ],
  barras: [
    {value: 1, text: 'Manter Atuais'},
    {value: 2, text: 'Gerar Novos'},
  ],
  // valor não é número porque a sp trata como string
  regime: [
    {text: 'MEI', value: 'MEI'},
    {text: 'Simples Nacional', value: 'SIMPLES'},
    {text: 'Regime Normal', value: 'NORMAL'},
  ],

  situacao: [
    {text: 'Ativa', value: 1},
    {text: 'Bloqueada', value: 2},
    {text: 'Encerrada', value: 3},
  ],
  parcelas: [
    {text: ' ', value: 0},
    {text: '1x', value: 1},
    {text: '2x', value: 2},
    {text: '3x', value: 3},
    {text: '4x', value: 4},
  ],
  responsavel: [
    {text: 'Interno - pela SaaSTec', value: 1},
    {text: 'Externo - por terceiro', value: 2},
  ],
}
